run_metadata_sample_name_column: Sample Name
run_metadata_marker_col_name: Metabarcoding Marker
run_metadata_sample_sheet_name: Sample Data Sheet Long
run_raw_data_path: # The raw data path of each marker folder (a lot are in a renamed folder)
  '18Sv4': /data/raw_data/20240328_JV_Run2_OCNMS_Arctic_eDNA/renamed/18Sv4/
  '18Sv9': /data/raw_data/20240328_JV_Run2_OCNMS_Arctic_eDNA/renamed/18Sv9/
  'COI': /data/raw_data/20240328_JV_Run2_OCNMS_Arctic_eDNA/renamed/COI/
  'ITS1': /data/raw_data/20240328_JV_Run2_OCNMS_Arctic_eDNA/renamed/ITS1/
  'Kelly16S': /data/raw_data/20240328_JV_Run2_OCNMS_Arctic_eDNA/renamed/Kelly16S/
  'Machida18S': /data/raw_data/20240328_JV_Run2_OCNMS_Arctic_eDNA/renamed/Machida18S/
  'MiFish': /data/raw_data/20240328_JV_Run2_OCNMS_Arctic_eDNA/renamed/MiFish/
  'Parada16S': /data/raw_data/20240328_JV_Run2_OCNMS_Arctic_eDNA/renamed/Parada16S/
run_sample_metadata_file_id: 1t_i2c0q-Oe4RHwUimBa9XuqRAlPXY1SiQ1m4dgkou9k
google_sheet_mapping_file_id: 19E4Yl1zPVQiskGGXAR94AeQGFHWrh-uWtJ9cuJYlJ48
run_name: run2 # for adding to the Positive control sample names
revamp_blast: True # if using the revamp blast-based taxonomy assignment then set this to True, otherwise False
ignore_markers: # Add Metabarcoding Marker name EXACTLY from run_sample_metadata_file if not submitting info for that marker
  - dLoop
asv_counts_tsvs_for_run: #dloop left out because Sean said dLoop did not work for Run2, keys match metabarcoding marker in metadata spreadsheet
  '18Sv4': /home/poseidon/mcallister/eDNA_bioinformatics/Run2/01_REVAMP/18Sv4/dada2/ASVs_counts.tsv
  '18Sv9': /home/poseidon/mcallister/eDNA_bioinformatics/Run2/01_REVAMP/18Sv9/dada2/ASVs_counts.tsv
  'COI': /home/poseidon/mcallister/eDNA_bioinformatics/Run2/01_REVAMP/COI/dada2/ASVs_counts.tsv
  'ITS1': //home/poseidon/mcallister/eDNA_bioinformatics/Run2/01_REVAMP/ITS1/dada2/ASVs_counts.tsv
  'Kelly16S': /home/poseidon/mcallister/eDNA_bioinformatics/Run2/01_REVAMP/Kelly16S/dada2/ASVs_counts.tsv
  'Machida18S': /home/poseidon/mcallister/eDNA_bioinformatics/Run2/01_REVAMP/Machida18S/dada2/ASVs_counts.tsv
  'MiFish': /home/poseidon/mcallister/eDNA_bioinformatics/Run2/01_REVAMP/MiFish/dada2/ASVs_counts.tsv
  'Parada16S': /home/poseidon/mcallister/eDNA_bioinformatics/Run2/01_REVAMP/Parada16S/dada2/ASVs_counts.tsv
otu_num_tax_assigned_files_for_run: # The files used to calculate the otu_num_tax_assigned - Sean said it depends on the version of taxonomy we are using
  '18Sv4': /home/poseidon/mcallister/eDNA_bioinformatics/Run2/01_REVAMP/18Sv4/ASV2Taxonomy/ASVs_counts_mergedOnTaxonomy.tsv
  '18Sv9': /home/poseidon/mcallister/eDNA_bioinformatics/Run2/01_REVAMP/18Sv9/ASV2Taxonomy/ASVs_counts_mergedOnTaxonomy.tsv
  'COI': /home/poseidon/mcallister/eDNA_bioinformatics/Run2/01_REVAMP/COI/ASV2Taxonomy/ASVs_counts_mergedOnTaxonomy.tsv
  'ITS1': /home/poseidon/mcallister/eDNA_bioinformatics/Run2/01_REVAMP/ITS1/ASV2Taxonomy/ASVs_counts_mergedOnTaxonomy.tsv
  'Kelly16S': /home/poseidon/mcallister/eDNA_bioinformatics/Run2/01_REVAMP/Kelly16S/ASV2Taxonomy/ASVs_counts_mergedOnTaxonomy.tsv
  'Machida18S': /home/poseidon/mcallister/eDNA_bioinformatics/Run2/01_REVAMP/Machida18S/ASV2Taxonomy/ASVs_counts_mergedOnTaxonomy.tsv
  'MiFish': /home/poseidon/mcallister/eDNA_bioinformatics/Run2/01_REVAMP/MiFish/ASV2Taxonomy/ASVs_counts_mergedOnTaxonomy.tsv
  'Parada16S': /home/poseidon/mcallister/eDNA_bioinformatics/Run2/01_REVAMP/Parada16S/ASV2Taxonomy/ASVs_counts_mergedOnTaxonomy.tsv

# path to json creds file for google sheets
json_creds: /home/poseidon/zalmanek/FAIRe-Mapping/credentials.json

# FAIRe template related
faire_template_file: /home/poseidon/zalmanek/FAIRe-Mapping/faire_template.xlsx
final_faire_template_path: /home/poseidon/zalmanek/FAIRe-Mapping/runs/run2/data/run2_faire.csv
