## M2-PPS-0423 Sample Metadata config.yaml ##
# Metadata file related 
sample_metadata_file: /home/poseidon/zalmanek/OME-EcoFOCI/EcoFOCI/data/1_SampleCollection/2023_M2_Spring-Summer_CruiseData/FinalOME_Merge_M2-PPS-0523.csv
sample_metadata_sample_name_column: Sample_Name # The name of the column in the metadata spreadsheet that lists the sample names
sample_metadata_file_neg_control_col_name: 'Negative_control' # Name of the column in the metadata spreadsheet for the boolean Negative Control
sample_metadata_cast_no_col_name: 'Cast_No.'  # is NA for PPS - looking into
sample_metadata_bottle_no_col_name: 'Rosette_position'
vessel_name: Dyson

# Extraction sheet related
extraction_metadata_google_sheet_id: 1KTs7LiITWi4DxmAjevH19HkWzKDY4CSkmd184dKmKxQ
extraction_name: AlaskaArctic22-23
extraction_cruise_key: .DY2306 #the name in the SampleName column of the extractions sheet to filter for the specific cruise
extraction_sample_name_col: 'FINAL Sample NAME'
extraction_conc_col_name: 'Qubit Conc.  (ng/Î¼L)' #to calculate average of extraction concentration
extraction_date_col_name: 'Extraction Date (Local)'
extraction_metadata_sheet_name: 'Extraction Sheets'
extraction_blank_vol_we_dna_ext: 1000 # The volume or mass of blanks extracted if there are blanks extracted
extraction_set_grouping_col_name: 'Extraction Set' # The name of the column that groups the samples together if they were extracted together

# mapping file related
google_sheet_mapping_file_id: 1qTAFyDNysLYAauicMZxc9nN5EsKfX4KEryyU4vYk9ZA
nc_samp_mat_process: 'placeholder' # mapping for negative controls for nc_samp_mapt_process. No .NC samples for this pps
nc_prepped_samp_store_dur: 'placeholder' # which columns the NC prepped samp_store_dur map to (will most likely be different than rest of samples because no ctd or bottle dates for NC). No .NC samples for this pps.

# FAIRe template related
faire_template_file: /home/poseidon/zalmanek/FAIRe-Mapping/faire_template.xlsx
final_faire_template_path: /home/poseidon/zalmanek/FAIRe-Mapping/projects/EcoFoci/m2_pps_0423/data/m2_pps_0423_faire.xlsx

# path to json creds file for google sheets
json_creds: /home/poseidon/zalmanek/FAIRe-Mapping/credentials.json