# Metadata file related 
sample_metadata_file: /home/poseidon/zalmanek/FAIRe-Mapping/skq21_12S/data/FinalOME_Merge_SKQ21-12S.csv
sample_metadata_sample_name_column: Sample_Name # The name of the column in the metadata spreadsheet that lists the sample names
sample_metadata_file_neg_control_col_name: 'Negative_control' # Name of the column in the metadata spreadsheet for the boolean Negative Control
sample_metadata_cast_no_col_name: 'Cast_No.'
sample_metadata_bottle_no_col_name: 'Rosette_position'
sample_metadata_depth_col_name: 'ctd_pressure' # only needed if using depth-1 to calculate minimum depth

# Extraction sheet related
# extraction_metadata_file: '/home/poseidon/zalmanek/FAIRe-Mapping/dy2012/faire_mapping_and_output/sample_metadata_files/SeanMcAllister_NOAA_finalConcentrations_June2021.xlsx - Info_ByPlate.csv'
extraction_metadata_google_sheet_id: 16Zg1MbMupnkXzuypTg4aF37OMyytPd-ZRqfz9QNX2oI
extraction_cruise_key: .SKQ2021 #the name in the SampleName column of the extractions sheet to filter for the specific cruise
extraction_sample_name_col: 'FINAL Sample NAME'
extraction_conc_col_name: 'Qubit Conc. (ng/Î¼L)' #to calculate average of extraction concentration
extraction_date_col_name: 'Extraction Date (Local)'
extraction_metadata_sheet_name: 'Sheet1'

# mapping file related
google_sheet_mapping_file_id: 13mqrAXO0dpE3vrCfG10Eze-KnYo-rAZmxb0HverQWy8 
nc_samp_mat_process:  'Water samples were filtered through a 0.22 micron sterivex filter using a peristaltic pump with tubing attached to the outlet end of the sterivex.' # mapping for negative controls for nc_samp_mapt_process
nc_prepped_samp_store_dur: 'verbatimEventDate | Extraction Date (Local)' # which columns the NC prepped samp_store_dur map to (will most likely be different than rest of samples because no ctd or bottle dates for NC)

# RunInfo
jv_run_sample_name_column: Sample Name
jv_index_name_col: Index Name
jv_raw_data_path: /data/raw_data/20250107_JV_Run3_FIXED_DEMULTIPLEXING/renamed/
jv_run_sample_metadata_file_id: 1t_i2c0q-Oe4RHwUimBa9XuqRAlPXY1SiQ1m4dgkou9k
run_short_cruise_name: SKQ2021 # the short cruise name in the jv run csv file to filter by cruise name


# FAIRe template related
faire_template_file: /home/poseidon/zalmanek/FAIRe-Mapping/faire_template.xlsx
final_faire_template_path: /home/poseidon/zalmanek/FAIRe-Mapping/skq21_12S/data/skq21_12S_faire.xlsx

# path to json creds file for google sheets
json_creds: /home/poseidon/zalmanek/FAIRe-Mapping/credentials.json