# Metadata file related 
sample_metadata_file: /home/poseidon/zalmanek/OME-EcoFOCI/EcoFOCI/data/1_SampleCollection/2021_SikuliaqDBO_CruiseData/2021_SikuliaqDBO_CruiseData/FinalOME_Merge_SKQ21-12S.csv
sample_metadata_sample_name_column: Sample_Name # The name of the column in the metadata spreadsheet that lists the sample names
sample_metadata_file_neg_control_col_name: 'Negative_control' # Name of the column in the metadata spreadsheet for the boolean Negative Control
sample_metadata_cast_no_col_name: 'Cast_No.'
sample_metadata_bottle_no_col_name: 'Rosette_position'
sample_metadata_depth_col_name: 'ctd_pressure' # only needed if using depth-1 to calculate minimum depth
vessel_name: Sikuliaq

# Extraction sheet related
# extraction_metadata_file: '/home/poseidon/zalmanek/FAIRe-Mapping/dy2012/faire_mapping_and_output/sample_metadata_files/SeanMcAllister_NOAA_finalConcentrations_June2021.xlsx - Info_ByPlate.csv'
extraction_metadata_google_sheet_id: 16Zg1MbMupnkXzuypTg4aF37OMyytPd-ZRqfz9QNX2oI
extraction_cruise_key: .SKQ2021 #the name in the SampleName column of the extractions sheet to filter for the specific cruise
extraction_sample_name_col: 'FINAL Sample NAME'
extraction_conc_col_name: 'Qubit Conc. (ng/Î¼L)' #to calculate average of extraction concentration
extraction_date_col_name: 'Extraction Date (Local)'
extraction_metadata_sheet_name: 'Sheet1'

# mapping file related
google_sheet_mapping_file_id: 13mqrAXO0dpE3vrCfG10Eze-KnYo-rAZmxb0HverQWy8 
nc_samp_mat_process:  'Water samples were filtered through a 0.22 micron sterivex filter using a peristaltic pump with tubing attached to the outlet end of the sterivex.' # mapping for negative controls for nc_samp_mapt_process
nc_prepped_samp_store_dur: 'verbatimEventDate | Extraction Date (Local)' # which columns the NC prepped samp_store_dur map to (will most likely be different than rest of samples because no ctd or bottle dates for NC)

# RunInfo
jv_run_sample_name_column: Sample Name
jv_index_name_col: Index Name
jv_raw_data_path: /data/raw_data/20240328_JV_Run2_OCNMS_Arctic_eDNA/renamed/
jv_run_sample_metadata_file_id: 1t_i2c0q-Oe4RHwUimBa9XuqRAlPXY1SiQ1m4dgkou9k
jv_run_name: pmel_ome_run2
run_short_cruise_name: SKQ2021 # the short cruise name in the jv run csv file to filter by cruise name
run_name: run2 # for adding to the Positive control sample names
revamp_blast: True # if using the revamp blast-based taxonomy assignment then set this to True, otherwise False
ignore_markers: # Add Metabarcoding Marker name EXACTLY from run_sample_metadata_file if not submitting info for that marker
  - dLoop
asv_counts_tsvs_for_run: #dloop left out because Sean said dLoop did not work for Run2, keys match metabarcoding marker in metadata spreadsheet
  '18S V4': /home/poseidon/mcallister/eDNA_bioinformatics/Run2/REVAMP/01_originalREVAMP/18Sv4/dada2/ASVs_counts.tsv
  '18S V9': /home/poseidon/mcallister/eDNA_bioinformatics/Run2/REVAMP/01_originalREVAMP/18Sv9/dada2/ASVs_counts.tsv
  'Leray CO1': /home/poseidon/mcallister/eDNA_bioinformatics/Run2/REVAMP/01_originalREVAMP/COI/dada2/ASVs_counts.tsv
  'ITS': /home/poseidon/mcallister/eDNA_bioinformatics/Run2/REVAMP/01_originalREVAMP/ITS1/dada2/ASVs_counts.tsv
  '16S Kelley': /home/poseidon/mcallister/eDNA_bioinformatics/Run2/REVAMP/01_originalREVAMP/Kelly16S/dada2/ASVs_counts.tsv
  '18S Machida': /home/poseidon/mcallister/eDNA_bioinformatics/Run2/REVAMP/01_originalREVAMP/Machida18S/dada2/ASVs_counts.tsv
  'MiFish 12S': /home/poseidon/mcallister/eDNA_bioinformatics/Run2/REVAMP/01_originalREVAMP/MiFish/dada2/ASVs_counts.tsv
  '16S Furhman': /home/poseidon/mcallister/eDNA_bioinformatics/Run2/REVAMP/01_originalREVAMP/Parada16S/dada2/ASVs_counts.tsv
otu_num_tax_assigned_files_for_run: # The files used to calculate the otu_num_tax_assigned - Sean said it depends on the version of taxonomy we are using
  '18S V4': /home/poseidon/mcallister/eDNA_bioinformatics/Run2/REVAMP/01_originalREVAMP/18Sv4/ASV2Taxonomy/ASVs_counts_mergedOnTaxonomy.tsv
  '18S V9': /home/poseidon/mcallister/eDNA_bioinformatics/Run2/REVAMP/01_originalREVAMP/18Sv9/ASV2Taxonomy/ASVs_counts_mergedOnTaxonomy.tsv
  'Leray CO1': /home/poseidon/mcallister/eDNA_bioinformatics/Run2/REVAMP/01_originalREVAMP/COI/ASV2Taxonomy/ASVs_counts_mergedOnTaxonomy.tsv
  'ITS': /home/poseidon/mcallister/eDNA_bioinformatics/Run2/REVAMP/01_originalREVAMP/ITS1/ASV2Taxonomy/ASVs_counts_mergedOnTaxonomy.tsv
  '16S Kelley': /home/poseidon/mcallister/eDNA_bioinformatics/Run2/REVAMP/01_originalREVAMP/Kelly16S/ASV2Taxonomy/ASVs_counts_mergedOnTaxonomy.tsv
  '18S Machida': /home/poseidon/mcallister/eDNA_bioinformatics/Run2/REVAMP/01_originalREVAMP/Machida18S/ASV2Taxonomy/ASVs_counts_mergedOnTaxonomy.tsv
  'MiFish 12S': /home/poseidon/mcallister/eDNA_bioinformatics/Run2/REVAMP/01_originalREVAMP/MiFish/ASV2Taxonomy/ASVs_counts_mergedOnTaxonomy.tsv
  '16S Furhman': /home/poseidon/mcallister/eDNA_bioinformatics/Run2/REVAMP/01_originalREVAMP/Parada16S/ASV2Taxonomy/ASVs_counts_mergedOnTaxonomy.tsv


# FAIRe template related
faire_template_file: /home/poseidon/zalmanek/FAIRe-Mapping/faire_template.xlsx
final_faire_template_path: /home/poseidon/zalmanek/FAIRe-Mapping/projects/EcoFoci/skq21_12S/data/skq21_12S_faire.xlsx

# path to json creds file for google sheets
json_creds: /home/poseidon/zalmanek/FAIRe-Mapping/credentials.json