## SKQ21_12S Sample Metadata config.yaml ##
# Metadata file related 
sample_metadata_file: /home/poseidon/zalmanek/OME-EcoFOCI/EcoFOCI/data/1_SampleCollection/2021_SikuliaqDBO_CruiseData/2021_SikuliaqDBO_CruiseData/FinalOME_Merge_SKQ21-12S.csv
sample_metadata_sample_name_column: Sample_Name # The name of the column in the metadata spreadsheet that lists the sample names
sample_metadata_file_neg_control_col_name: 'Negative_control' # Name of the column in the metadata spreadsheet for the boolean Negative Control
sample_metadata_cast_no_col_name: 'Cast_No.'
sample_metadata_bottle_no_col_name: 'Rosette_position'
vessel_name: Sikuliaq

# Extraction sheet related
extraction_metadata_google_sheet_id: 16Zg1MbMupnkXzuypTg4aF37OMyytPd-ZRqfz9QNX2oI
extraction_name: SKQ21
extraction_cruise_key: .SKQ2021 #the name in the SampleName column of the extractions sheet to filter for the specific cruise
extraction_sample_name_col: 'FINAL Sample NAME'
extraction_conc_col_name: 'Qubit Conc. (ng/μL)' #to calculate average of extraction concentration
extraction_date_col_name: 'Extraction Date (Local)'
extraction_metadata_sheet_name: 'Sheet1'
extraction_blank_vol_we_dna_ext: 1000 # The volume or mass of blanks extracted if there are blanks extracted
extraction_set_grouping_col_name: 'Extraction Set' # The name of the column that groups the samples together if they were extracted together

# Missing Mid.NC.SKQ21 sample
missing_extractions:
  - missing_extraction_google_sheet_id: 1aXN_HmGRDgDLvkz1Dbkje6R7rUUg9mNNc630YN8HvFE
    missing_extraction_sheet_name: Sheet1
    missing_extraction_samp_names:  # The missing sample names with the new extracton sheet samp name as key and the sample metadata samp name as value (in case they are different)
      'Mid.NC.SKQ21': 'MID.NC.SKQ2021'
    missing_ext_col_to_main_ext_col: # only if mapping file is the same for different extractions and column names might differ across extractions - only need columns that are used in mapping file
      'Extraction Date (Local)': 'Extraction Date (Local)'
      'Qubit Conc.  (ng/μL)': 'Qubit Conc. (ng/μL)'
      'Extraction Set': 'Extraction Set'
      'FINAL Sample NAME': 'FINAL Sample NAME'

samp_store_dur_sheet_info: # Include only if cruise sample info in a samp_store_dur sheet that Shannon created
  google_sheet_id: 1c0C2HdmwQis9siwPPv5l1dhVZEfAZAeov3tGnl2Hgdw
  samp_name_col: FINAL Sample NAME
  samp_stor_dur_col: sample_stor_dur
  dur_units: hour

# mapping file related
google_sheet_mapping_file_id: 13mqrAXO0dpE3vrCfG10Eze-KnYo-rAZmxb0HverQWy8 
nc_samp_mat_process:  'Water samples were filtered through a 0.22 micron sterivex filter using a peristaltic pump with tubing attached to the outlet end of the sterivex.' # mapping for negative controls for nc_samp_mapt_process
nc_prepped_samp_store_dur: 'verbatimEventDate | Extraction Date (Local)' # which columns the NC prepped samp_store_dur map to (will most likely be different than rest of samples because no ctd or bottle dates for NC)

# Station reference file
station_name_reference_google_sheet_id: 1bJiX5pXpUuk74tbuoiYRc7iNXAVYU2dD8nTnZAFpZg8

# FAIRe template related
faire_template_file: /home/poseidon/zalmanek/FAIRe-Mapping/faire_template.xlsx
final_faire_template_path: /home/poseidon/zalmanek/FAIRe-Mapping/projects/EcoFoci/skq21_12S/data/skq21_12S_faire.xlsx

# path to json creds file for google sheets
json_creds: /home/poseidon/zalmanek/FAIRe-Mapping/credentials.json