#TODO: add OSU876, OSU894, OSU1034, and OSU1037 to associated_sequencing_runs after Sean gets this info to you

datasets: # a list of sample_metadata.csvs and their associated experimentRun csvs
  sample_metadata_csvs:
    - cruise_name: dy2012
      sample_metadata_csv_path: /home/poseidon/zalmanek/FAIRe-Mapping/projects/EcoFoci/dy2012/data/dy2012_faire.csv
    - cruise_name: dy2206
      sample_metadata_csv_path: /home/poseidon/zalmanek/FAIRe-Mapping/projects/EcoFoci/dy2206/data/dy2206_faire.csv
    - cruise_name: dy2209
      sample_metadata_csv_path: /home/poseidon/zalmanek/FAIRe-Mapping/projects/EcoFoci/dy2209/data/dy2209_faire.csv
    - cruise_name: dy2306
      sample_metadata_csv_path: /home/poseidon/zalmanek/FAIRe-Mapping/projects/EcoFoci/dy2306/data/dy2306_faire.csv
    - cruise_name: m2_pps_0523
      sample_metadata_csv_path: /home/poseidon/zalmanek/FAIRe-Mapping/projects/EcoFoci/m2_pps_0523/data/m2_pps_0523_faire.csv
    - cruise_name: no201
      sample_metadata_csv_path: /home/poseidon/zalmanek/FAIRe-Mapping/projects/EcoFoci/no201/data/no201_faire.csv
    - cruise_name: skq21_12S
      sample_metadata_csv_path: /home/poseidon/zalmanek/FAIRe-Mapping/projects/EcoFoci/skq21_12S/data/skq21_12S_faire.csv
    - cruise_name: skq23_12S
      sample_metadata_csv_path: /home/poseidon/zalmanek/FAIRe-Mapping/projects/EcoFoci/skq23_12S/data/skq23_12S_faire.csv
  associated_sequencing_csvs:
    - sequencing_run_name: osu867
      sequence_run_csv_path: /home/poseidon/zalmanek/FAIRe-Mapping/runs/osu867/data/osu867_faire.csv
    - sequencing_run_name: osu873
      sequence_run_csv_path: /home/poseidon/zalmanek/FAIRe-Mapping/runs/osu873/data/osu873_faire.csv
    - sequencing_run_name: osu1089
      sequence_run_csv_path: /home/poseidon/zalmanek/FAIRe-Mapping/runs/osu1089/data/osu1089_faire.csv
    - sequencing_run_name: run2
      sequence_run_csv_path: /home/poseidon/zalmanek/FAIRe-Mapping/runs/run2/data/run2_faire.csv
    - sequencing_run_name: run3
      sequence_run_csv_path: /home/poseidon/zalmanek/FAIRe-Mapping/runs/run3/data/run3_faire.csv
    - sequencing_run_name: run4
      sequence_run_csv_path: /home/poseidon/zalmanek/FAIRe-Mapping/runs/run4/data/run4_faire.csv

# Add samples that have mismatching names between the Sample Metadata and the Experiment Run Metadata
# Add sample metadata name as key, and experiment run metadata name as value
mismatch_sample_names: 
  Larson NC1: NC1
  Larson NC2: NC2
  Larson NC3: NC3
  Larson NC4: NC4 # this one is really the only once that matters being changed, because the rest get pooled, but I still wanted them to match
  Larson NC5: NC5

#pooled samples dict - all pooled samples applicable to this project and the subsamples they make up
# if sample names are in the mismatch - add the updated sample name as the value here.
pooled_samps:
  - pooled_samp_name: RC0083_NC_pool
    samps_that_were_pooled:
    - E1573.NC.RC0083
    - E1451.NC.RC0083
    - E1500.NC.RC0083
    sample_category: negative control
    cont_type: field negative
  - pooled_samp_name: BlankAlaskaSet_NC_pool
    samps_that_were_pooled:
    - Blank.Alaska.Set7
    - BlankAlaska.Set9
    - Blank.Alaska.Set11
    sample_category: negative control
    cont_type: extraction negative
  - pooled_samp_name: Dyson_NC_pool
    samps_that_were_pooled:
    - E1717.NC.DY2306
    - E1157.NC.DY2206
    sample_category: negative control
    cont_type: field negative
  - pooled_samp_name: SKQ23_NC_pool
    samps_that_were_pooled:
    - E2028.NC.SKQ23-12S
    - E2030.NC.SKQ23-12S
    sample_category: negative control
    cont_type: field negative
  - pooled_samp_name: SKQ_NC_pool
    samps_that_were_pooled:
    - NC2
    - NC3
    - NC5
    sample_category: negative control
    cont_type: extraction negative

faire_template_file: /home/poseidon/zalmanek/FAIRe-Mapping/faire_template.xlsx
final_faire_template_path: /home/poseidon/zalmanek/FAIRe-Mapping/projects/EcoFoci/data/ecoFoci_faire.xlsx

json_creds: /home/poseidon/zalmanek/FAIRe-Mapping/credentials.json
 
 
