## Aquamonitor Sample Metadata config.yaml ##
# Metadata file related 
sample_metadata_file: /home/poseidon/zalmanek/FAIRe-Mapping/projects/FloatingSamples/mixed_sean/Orphan_Projects_Metadata.csv
sample_metadata_sample_name_column: samp_name # The name of the column in the metadata spreadsheet that lists the sample names
sample_metadata_file_neg_control_col_name: 'Negative control' # Name of the column in the metadata spreadsheet for the boolean Negative Control
sample_metadata_cast_no_col_name: 'ctd_cast_number'
sample_metadata_bottle_no_col_name: 'ctd_bottle_number'
vessel_name: vessel

extractions: 
  - extraction_name:  OSU # the name of the extraction performed (for the extract_id)
    extraction_metadata_google_sheet_id: 1qLZzrYk7s9b68g1oW32fer68bfLKSGzTsJDlJRYmOzg
    extraction_cruise_key: 
      - .AX17
      - .LO18
      - .VA19
      - .DA19
    extraction_sample_name_col: Sample
    extraction_conc_col_name: ng/uL #to calculate average of extraction concentration
    extraction_date_col_name: Date
    extraction_metadata_sheet_name: Info_ByPlate
    extraction_blank_vol_we_dna_ext: 1000 # The volume or mass of blanks extracted if there are blanks extracted
    extraction_set_grouping_col_name: 'Plate' # The name of the column that groups the samples together if they were extracted together
  - extraction_name: WCOA21
    extraction_metadata_google_sheet_id: 1aXN_HmGRDgDLvkz1Dbkje6R7rUUg9mNNc630YN8HvFE
    extraction_cruise_key: 
      - .WCOA21
      - .NA128
      - .Chaba22
    extraction_sample_name_col: 'FINAL Sample NAME'
    extraction_conc_col_name: 'Qubit Conc. (ng/μL)' #to calculate average of extraction concentration
    extraction_date_col_name: 'Extraction Date (Local)'
    extraction_metadata_sheet_name: 'Sheet1'
    extraction_blank_vol_we_dna_ext: 1000 # The volume or mass of blanks extracted if there are blanks extracted
    extraction_set_grouping_col_name: 'Extraction Set' # The name of the column that groups the samples together if they were extracted together
  - extraction_name: NA128
    extraction_metadata_google_sheet_id: 1_Oa4CievaRjUFxI7xceAA3NIS6IlUdobtA0_Ahi1arI
    extraction_cruise_key: .NA128
    extraction_sample_name_col: 'FINAL Sample NAME'
    extraction_conc_col_name: 'Qubit Conc. (ng/μL)' #to calculate average of extraction concentration
    extraction_date_col_name: 'Extraction Date (Local)'
    extraction_metadata_sheet_name: 'Extraction Sheet'
    extraction_blank_vol_we_dna_ext: 1000 # The volume or mass of blanks extracted if there are blanks extracted
    extraction_set_grouping_col_name: 'Extraction Set' # The name of the column that groups the samples together if they were extracted together
  - extraction_name: Axial2022
    extraction_metadata_google_sheet_id: 1LftDxnIXT6rsPExrotJDRuGyzyxo77kl_OBlsbZDe6c
    extraction_cruise_key: .AX22
    extraction_sample_name_col: 'FINAL Sample NAME (24 samples)'
    extraction_conc_col_name: 'Qubit Conc. (ng/μL)' #to calculate average of extraction concentration
    extraction_date_col_name: 'Extraction Date (Local)'
    extraction_metadata_sheet_name: 'Extraction Sheet'
    extraction_blank_vol_we_dna_ext: 1000 # The volume or mass of blanks extracted if there are blanks extracted
    extraction_set_grouping_col_name: 'Extraction Set' # The name of the column that groups the samples together if they were extracted together
  - extraction_name: CrabLightTraps_H20
    extraction_metadata_google_sheet_id: 13SHzh4iojBjPoqq0H83m21mGHTBxDxxDJbauPYI3aNY
    extraction_cruise_key: 
      - .LT0625
      - .LT0710
    extraction_sample_name_col: 'FINAL Sample NAME'
    extraction_conc_col_name: 'Qubit Conc. (ng/μL)' #to calculate average of extraction concentration
    extraction_date_col_name: 'Extraction Date (Local)'
    extraction_metadata_sheet_name: 'eDNA from H2O'
    extraction_blank_vol_we_dna_ext: 1000 # The volume or mass of blanks extracted if there are blanks extracted
    extraction_set_grouping_col_name: 'Extraction Set' # The name of the column that groups the samples together if they were extracted together
  - extraction_name: CrabLightTraps_EtOH
    extraction_metadata_google_sheet_id: 13SHzh4iojBjPoqq0H83m21mGHTBxDxxDJbauPYI3aNY
    extraction_cruise_key: 
      - .LT0625
      - .LT0710
      - .WCOA21
      - '.'
    extraction_sample_name_col: 'FINAL Sample NAME'
    extraction_conc_col_name: 'Qubit Conc. (ng/μL)' #to calculate average of extraction concentration
    extraction_date_col_name: 'Extraction Date (Local)'
    extraction_metadata_sheet_name: 'eDNA from EtOH'
    extraction_blank_vol_we_dna_ext: 1000 # The volume or mass of blanks extracted if there are blanks extracted
    extraction_set_grouping_col_name: 'Extraction Set' # The name of the column that groups the samples together if they were extracted together
  - extraction_name: Smith-Root
    extraction_metadata_google_sheet_id: 1xHmA4KAGk6DaC8oXXoZAw9Eo_5O859BGb9QdB8NoF0I
    extraction_cruise_key: 
      - .SRMC24
      - .SROC24
      - .SRGG24
      - .SRLW24
    extraction_sample_name_col: 'FINAL Sample NAME'
    extraction_conc_col_name: 'Qubit Conc. (ng/μL)' #to calculate average of extraction concentration
    extraction_date_col_name: 'Extraction Date'
    extraction_metadata_sheet_name: 'Extraction Sheet'
    extraction_blank_vol_we_dna_ext: 1000 # The volume or mass of blanks extracted if there are blanks extracted
    extraction_set_grouping_col_name: 'Extraction Set' # The name of the column that groups the samples together if they were extracted together
  - extraction_name: QiavacTest
    extraction_metadata_google_sheet_id: 1r94A1MB5Gih0djnwEdxB15gv_h16EQ1qkUWZ8VUlW3I
    extraction_cruise_key: 
      - .Kotzebue23
      - .QIAvac Test
    extraction_sample_name_col: 'FINAL Sample NAME'
    extraction_conc_col_name: 'Qubit Conc. (ng/μL)' #to calculate average of extraction concentration
    extraction_date_col_name: 'Extraction Date (Local)'
    extraction_metadata_sheet_name: 'Sheet1'
    extraction_blank_vol_we_dna_ext: 1000 # The volume or mass of blanks extracted if there are blanks extracted
    extraction_set_grouping_col_name: 'Extraction Set' # The name of the column that groups the samples together if they were extracted together
  - extraction_name: ZymoPositiveControls
    extraction_metadata_google_sheet_id: 1t3B8o0bmiBcUmY4EUrR_3pCyzX_51qy14OImsLZ_ZBU
    extraction_cruise_key: .ZymoPC
    extraction_sample_name_col: 'FINAL Sample NAME'
    extraction_conc_col_name: 'Qubit Conc. (ng/μL)' #to calculate average of extraction concentration
    extraction_date_col_name: 'Extraction Date (Local)'
    extraction_metadata_sheet_name: 'Extraction Sheet'
    extraction_blank_vol_we_dna_ext: 1000 # The volume or mass of blanks extracted if there are blanks extracted
    extraction_set_grouping_col_name: 'Extraction Set' # The name of the column that groups the samples together if they were extracted together

# samp_store_dur_sheet_info: # Include only if cruise sample info in a samp_store_dur sheet that Shannon created
#   google_sheet_id: 1c0C2HdmwQis9siwPPv5l1dhVZEfAZAeov3tGnl2Hgdw
#   samp_name_col: FINAL Sample NAME
#   samp_stor_dur_col: sample_stor_dur
#   dur_units: hour

# mapping file related
google_sheet_mapping_file_id: 1vfdQRReGUEl88axV-DAz1hGMhGznh17UfrYWyuSs-Mw
nc_samp_mat_process:  'missing: not collected' # mapping for negative controls for nc_samp_mapt_process
nc_prepped_samp_store_dur: 'missing: not collected' # which columns the NC prepped samp_store_dur map to (will most likely be different than rest of samples because no ctd or bottle dates for NC)

# Station reference file
# station_name_reference_google_sheet_id: 1bJiX5pXpUuk74tbuoiYRc7iNXAVYU2dD8nTnZAFpZg8

# FAIRe template related
faire_template_file: /home/poseidon/zalmanek/FAIRe-Mapping/faire_template.xlsx
final_faire_template_path: /home/poseidon/zalmanek/FAIRe-Mapping/projects/FloatingSamples/AquaM/data/AquaM_faire.xlsx

# path to json creds file for google sheets
json_creds: /home/poseidon/zalmanek/FAIRe-Mapping/credentials.json