# Use same config file as projectMapper
logging_directory: /home/poseidon/zalmanek/FAIRe-Mapping/runs/osu867/ncbi_mapping/ncbi_submission_data/logging/
datasets: # a list of sample_metadata.csvs and their associated experimentRun csvs
  sample_metadata_csvs:
    - cruise_name: dy2012
      sample_metadata_csv_path: /home/poseidon/zalmanek/FAIRe-Mapping/projects/EcoFoci/dy2012/data/dy2012_faire.csv
  associated_sequencing_csvs:
    - sequencing_run_name: osu867
      sequence_run_csv_path: /home/poseidon/zalmanek/FAIRe-Mapping/runs/osu867/data/osu867_faire.csv

faire_template_file: /home/poseidon/zalmanek/FAIRe-Mapping/faire_template.xlsx
final_faire_template_path: # nothing here because final_faire_template_path is not needed for ncbi

json_creds: /home/poseidon/zalmanek/FAIRe-Mapping/credentials.json