## FAIRe sample fields that will have the same mapping as the other samples (e.g. won't be not applicable)

nc_faire_field_cols = ['samp_name',
                    'samp_category',
                    'neg_cont_type',
                    'verbatimEventDate',
                    'verbatimEventTime',
                    'eventDate',
                    'eventDurationValue',
                    'habitat_natural_artificial_0_1',  # will be 1 for NC's
                    'samp_collect_method',
                    'samp_size',
                    'samp_size_unit',
                    'samp_store_temp',
                    'samp_store_sol',
                    'samp_store_loc',
                    'samp_store_method_additional',
                    'samp_mat_process', # remove niskin info from it
                    'filter_passive_active_0_1',
                    'pump_flow_rate',
                    'pump_flow_rate_unit',
                    'prefilter_material',
                    'size_frac_low',
                    'size_frac',
                    'filter_diameter',
                    'filter_surface_area',
                    'filter_material',
                    'filter_name',
                    'precip_chem_prep',
                    'precip_force_prep',
                    'precip_time_prep',
                    'precip_temp_prep',
                    'prepped_samp_store_temp',
                    'prepped_samp_store_sol',
                    'prepped_samp_store_dur',
                    'prep_method_additional',
                    'assay_name',
                    'date_ext',
                    'samp_vol_we_dna_ext',
                    'samp_vol_we_dna_ext_unit',
                    'nucl_acid_ext_lysis',
                    'nucl_acid_ext_sep',
                    'nucl_acid_ext',
                    'nucl_acid_ext_kit',
                    'nucl_acid_ext_modify',
                    'dna_cleanup_0_1',
                    'dna_cleanup_method',
                    'concentration',
                    'concentration_unit',
                    'concentration_method',
                    'ratioOfAbsorbance260_280',
                    'pool_dna_num',
                    'nucl_acid_ext_method_additional'
                    ]


assay_names = {'AmaralZettler_phytoplankton_18S_V9',
               'Baker_marmam_dLoop',
               'Kelly_metazoan_mt16S',
               'LerayFolmer_metazoan_COI',
               'Machida_metazoan_18S_V8',
               'MiFish_UniversalTeleost_12S',
               'Parada_universal_SSU16S_V4',
               'Stoeck_phytoplankton_18S_V4',
               'WhiteSterling_phytoplankton_ITS1',
}
