run_metadata_csvs: # The path to the run(s) that will be submitted to NCBI (for one submission)
  - /home/poseidon/zalmanek/FAIRe-Mapping/runs/run4/data/run4_faire.csv

sample_metadata_project_csvs: # The path to the final sample metadata for all projects captured by the run. MUST BE THE FINAL PROJECT SAMPLE METADATA CSV! Not the intermittent one per cruise (this will be missing assay_name, rel_cont_id, etc.)
  - /home/poseidon/zalmanek/FAIRe-Mapping/projects/EcoFoci/data/sampleMetadata_OME_eDNA_EcoFOCI_2020-2023.csv
  - /home/poseidon/zalmanek/FAIRe-Mapping/projects/AK_Carbon/data/sampleMetadata_OME_eDNA_PMELCarbon_RachelCarson_2022.csv

assay_type: metabarcoding # e.g. metabarcoding or qPCR
bioproject_accession: ADD!!!!!! # NCBI bioproject acccession number

library_prep_info: # info that points to the github repo with the library prep BeBOP. Will get via API
  owner: marinednadude
  repo: Jonah-Ventures-Library-Preparation
  file_path: Jonah-Ventures-Library-NovaSeq-Preparation-BeBOP.md

ncbi_sample_excel_save_path: /home/poseidon/zalmanek/FAIRe-Mapping/runs/run4/ncbi_mapping/ncbi_submission_data/run4_MIMARKS.survey.water.6.0.xlsx
ncbi_sra_excel_save_path: /home/poseidon/zalmanek/FAIRe-Mapping/runs/run4/ncbi_mapping/ncbi_submission_data/run4_SRA_metadata.xlsx

