# 4 Experiment Metadata RunInfo
run_metadata_sample_name_column: Sample Name
run_metadata_marker_col_name: Metabarcoding Marker
run_metadata_sample_sheet_name: Sample Data Sheet Long
run_raw_data_path: # The raw data path of each marker folder (a lot are in a renamed folder)
  '18Sv4': /data/raw_data/20250118_JV_Run4_Arctic_eDNA/renamed/JVB4314_18Sv4/
  'COI': /data/raw_data/20250118_JV_Run4_Arctic_eDNA/renamed/JVB4314_UniCOI/
  'ITS1': /data/raw_data/20250118_JV_Run4_Arctic_eDNA/renamed/JVB4314_ITS1_diatom/
  'Machida18S': /data/raw_data/20250118_JV_Run4_Arctic_eDNA/renamed/JVB4314_18SMachida/
  'MiFish': /data/raw_data/20250118_JV_Run4_Arctic_eDNA/renamed/JVB4314_MiFishU_F2/
  'Parada16S': /data/raw_data/20250118_JV_Run4_Arctic_eDNA/renamed/JVB4314_16Sv4v5/
run_sample_metadata_file_id: 1XWUAaidPfeRdAsCI-NRAzRIz4QK6OxGg4FGWCxuPkTg
google_sheet_mapping_file_id: 1z_On8iNWaFHoELm1E0aaAosgb0qJwGuEJ6QT86U04mc
run_name: run4 # for adding to the Positive control sample names
revamp_blast: True # if using the revamp blast-based taxonomy assignment then set this to True, otherwise False
ignore_markers: # Add Metabarcoding Marker name EXACTLY from run_sample_metadata_file if not submitting info for that marker
  - dLoop
asv_counts_tsvs_for_run: #dloop left out because Sean said dLoop did not work for Run2, keys match metabarcoding marker in metadata spreadsheet
  '18Sv4': /home/poseidon/mcallister/eDNA_bioinformatics/Run4/01_REVAMP/18Sv4_REVAMP_out/dada2/ASVs_counts.tsv
  'COI': /home/poseidon/mcallister/eDNA_bioinformatics/Run4/01_REVAMP/COI_REVAMP_out/dada2/ASVs_counts.tsv
  'ITS1': /home/poseidon/mcallister/eDNA_bioinformatics/Run4/01_REVAMP/ITS1_REVAMP_out/dada2/ASVs_counts.tsv
  'Machida18S': /home/poseidon/mcallister/eDNA_bioinformatics/Run4/01_REVAMP/Machida18S_REVAMP_out/dada2/ASVs_counts.tsv
  'MiFish': /home/poseidon/mcallister/eDNA_bioinformatics/Run4/01_REVAMP/MiFish_REVAMP_out/dada2/ASVs_counts.tsv
  'Parada16S': /home/poseidon/mcallister/eDNA_bioinformatics/Run4/01_REVAMP/Parada16S_REVAMP_out/dada2/ASVs_counts.tsv
otu_num_tax_assigned_files_for_run: # The files used to calculate the otu_num_tax_assigned - Sean said it depends on the version of taxonomy we are using
  '18Sv4': /home/poseidon/mcallister/eDNA_bioinformatics/Run4/01_REVAMP/18Sv4_REVAMP_out/ASV2Taxonomy/ASVs_counts_mergedOnTaxonomy.tsv
  'COI': /home/poseidon/mcallister/eDNA_bioinformatics/Run4/01_REVAMP/COI_REVAMP_out/ASV2Taxonomy/ASVs_counts_mergedOnTaxonomy.tsv
  'ITS1': /home/poseidon/mcallister/eDNA_bioinformatics/Run4/01_REVAMP/ITS1_REVAMP_out/ASV2Taxonomy/ASVs_counts_mergedOnTaxonomy.tsv
  'Machida18S': /home/poseidon/mcallister/eDNA_bioinformatics/Run4/01_REVAMP/Machida18S_REVAMP_out/ASV2Taxonomy/ASVs_counts_mergedOnTaxonomy.tsv
  'MiFish': /home/poseidon/mcallister/eDNA_bioinformatics/Run4/01_REVAMP/MiFish_REVAMP_out/ASV2Taxonomy/ASVs_counts_mergedOnTaxonomy.tsv
  'Parada16S': /home/poseidon/mcallister/eDNA_bioinformatics/Run4/01_REVAMP/Parada16S_REVAMP_out/ASV2Taxonomy/ASVs_counts_mergedOnTaxonomy.tsv

# path to json creds file for google sheets
json_creds: /home/poseidon/zalmanek/FAIRe-Mapping/credentials.json

# FAIRe template related
faire_template_file: /home/poseidon/zalmanek/FAIRe-Mapping/faire_template.xlsx
final_faire_template_path: /home/poseidon/zalmanek/FAIRe-Mapping/runs/run4/data/run4_faire.csv