name: Exp Run Validation
on:
  pull_request:
    paths: 
      - 'runs/**/data/*.csv'
      - 'projects/**/**/data/*.csv'

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  validate-sample-metadata-csv:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        lfs: true

    - name: Download LFS files
      run: git lfs pull
        
    - name: Set up Conda with caching
      uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: true
        activate-environment: faire_mapping
        environment-file: environment.yml
        python-version: 3.11
        auto-activate-base: false
        use-mamba: true
        
    - name: Cache conda environment
      uses: actions/cache@v3
      with:
        path: /usr/share/miniconda/envs/faire_mapping
        key: conda-${{ runner.os }}-${{ hashFiles('environment.yml') }}
        restore-keys: |
          conda-${{ runner.os }}-
          
    - name: Install dependencies
      shell: bash -l {0}
      run: | 
        conda list | grep pandas || {
          echo "Installing dependencies..."
          conda install -c conda-forge -c anaconda -c bioconda pandas pyyaml openpyxl isodate requests beautifulsoup4 shapely geopandas h5netcdf netcdf4 xarray pydantic 
          pip install google-api-python-client google-auth-oauthlib gspread oauth2client python-frontmatter gsw bioawk
        }
        
    - name: Get changed CSV files
      id: changed-files
      uses: tj-actions/changed-files@v40
      with:
        files: | 
          runs/**/data/*.csv
          projects/**/**/data/*.csv
          
    - name: Validate CSV files
      if: steps.changed-files.outputs.any_changed == 'true'
      shell: bash -l {0}
      run: | 
        echo "🔍 Found changed CSV files:"
        echo "${{ steps.changed-files.outputs.all_changed_files }}"
        echo ""
        
        # Initialize variables
        overall_success=true
        validation_summary=""
        
        # Function to determine model class based on file path
        get_model_class() {
          local file_path="$1"
          case "$file_path" in
            *runs/*/data/*.csv)
              echo "ExperimentRunMetadata"
              ;;
            *projects/*/data/*.csv)
              echo "SampleMetadata"
              ;;
            *)
              echo "SampleMetadata"  # Default fallback
              ;;
          esac
        }
        
        # Validate each file
        for csv_file in ${{ steps.changed-files.outputs.all_changed_files }}; do
          echo "======================================"
          echo "📋 Validating: $csv_file"
          
          model_class=$(get_model_class "$csv_file")
          echo "🔎 Using model class: $model_class"
          
          # Run validation and capture output
          if output=$(python validators/csv_validator.py "$csv_file" "$model_class" 2>&1); then
            echo "✅ $csv_file passed validation"
            status="✅ PASSED"
            if echo "$output" | grep -q "warnings"; then
              status="⚠️ PASSED (with warnings)"
            fi
          else
            echo "❌ $csv_file failed validation"
            echo "$output"
            overall_success=false
            status="❌ FAILED"
          fi
          
          # Add to summary
          validation_summary+="**$csv_file** ($model_class): $status"$'\n'
          validation_summary+='```'$'\n'
          validation_summary+="$output"$'\n'
          validation_summary+='```'$'\n\n'
        done
        
        # Save results for PR comment
        {
          echo "VALIDATION_SUMMARY<<EOF"
          echo "$validation_summary"
          echo "EOF"
        } >> $GITHUB_ENV
        
        echo "OVERALL_SUCCESS=$overall_success" >> $GITHUB_ENV
        
        # Print final summary
        echo "================================================================="
        echo "📊 VALIDATION SUMMARY"
        echo "================================================================="
        if [ "$overall_success" = true ]; then
          echo "🎉 All CSV files passed validation!"
        else
          echo "❌ Some CSV files failed validation. Please fix the errors before merging."
          exit 1
        fi
        
    - name: Comment on PR
      if: github.event_name == 'pull_request' && steps.changed-files.outputs.any_changed == 'true'
      uses: actions/github-script@v7
      with:
        script: |
          const summary = process.env.VALIDATION_SUMMARY;
          const success = process.env.OVERALL_SUCCESS === 'true';
          
          const emoji = success ? '✅' : '❌';
          const title = success ? 
            'All CSV files passed validation!' : 
            'Some CSV files failed validation';
          
          const body = `${emoji} **CSV Data Validation Results**
          
          **${title}**
          
          <details>
          <summary>📋 Detailed Results</summary>
          
          ${summary}
          
          </details>`;
          
          await github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: body
          });
